### ISSUE TITLE
Utilization review is possible in steampipe or not

### ISSUE THREAD

**Issue by Niba-nazar** [turbot/steampipe-mod-digitalocean-thrifty#27]
Hi,

Is it possible to know utilization reviews on steampipe, to get a summary or report on which servers/resources are truly being used and which are sitting idle?

**Comment by misraved** [comment]
Welcome to Steampipe @Niba-nazar, great to see you using the DigitalOcean mod 👍 .

At present we do have a few controls that check if the resources are available or idle. You could lean onto the `block_storage_volume_inactive_and_unused` control which enlists the volumes which are unattached.

 We do have good dashboards in https://github.com/turbot/steampipe-mod-digitalocean-insights/tree/main/dashboards which provide an in-depth overview of digitalocean resources.
 
 @Niba-nazar are you looking out for some specific resources? Currently the plugin supports [22 tables](https://hub.steampipe.io/plugins/turbot/digitalocean/tables), we will be more than happy to add controls/queries for the resources you are looking out for 👍 .

**Comment by rinshadka** [comment]
Hi @misraved,  is there any possibility to check or bring a feature for identifying **idle** resources like - `a running droplet` which is not being used and can be flagged as idle depending upon the measurements of its CPU/RAM consumption etc..

**Comment by misraved** [comment]
Welcome to Steampipe @rinshadka 👍 . I think we need to add new tables to the digital ocean plugin to query CPU/RAM consumption. 

From an initial scan, I came across this [API](https://github.com/digitalocean/godo/blob/main/metrics/metrics.go) which can provide valuable insights on droplet metrics.

Could you please open an issue in https://github.com/turbot/steampipe-plugin-digitalocean/issues to add new tables for retrieving droplet metrics?

**Comment by Niba-nazar** [comment]
hi,

Thank you @misraved for the reply.

Is it possible to get  **network** utilization reports through SQL? Also would like to know if steampipe is providing any  SQLite backend support or SQLite as Destination

**Comment by misraved** [comment]
Hello @Niba-nazar, thanks for the reply 👍 .

Starting with the second part of the question, I think if you use Steampipe in the service mode, you will be able to connect it to any database management tool - https://steampipe.io/docs/managing/service#service-mode

I think Steampipe Cloud would be a great fit for your use case, more examples can be found here - https://steampipe.io/docs/cloud/integrations/overview

For the network utilization section - Currently, we don't have support for network utilization components in https://hub.steampipe.io/plugins/turbot/digitalocean/tables/digitalocean_vpc table. I will dig deep into what APIs we could add which would provide the correct information.

**Comment by Niba-nazar** [comment]
Hi @misraved ,

Thanks for the reply.

I can use PostgreSQL to connect to the "steampipe" database. I would like to learn more via sqlite3, though. Would you kindly help me understand how to use a sqlite3 database with steampipe?

**Comment by misraved** [comment]
Relevant slack thread - https://steampipe.slack.com/archives/C01UECB59A7/p1669292206131539
